# Copyright 2022 Ben Woodward. All rights reserved.
# Use of this source code is governed by a GPL style
# license that can be found in the LICENSE file.
title = "n1cklim's photography repo"
baseURL = "https://photographyrepo.netlify.app/"
languageCode = "en-us"
paginate = 20
paginatePath = ""
[permalinks]
  img = "/img/:title/"
